### PR TITLE
Added authentication logic to Pelops

### PR DESCRIPTION
**Pull request by joethopkins**
Hi,

You will find an implementation for performing Cassandra authentication using Pelops.  I'm using Pelops in performance marketing / ad serving applications at Mediatrust (http://www.mediatrust.com).  I have an immediate need to add authentication to Cassandra nodes in our next release.  It would be great if I could get this or something like this added to the s7 master so that I don't have to support my own code base for my authentication needs.

I used an interface IConnectionAuthenticator in order to support forms of authentication other than simple that might be added to Cassandra in the future.  I first looked at adding it to the ConnectionPool but it seemed less intrusive to the code based and a better approach to add it at the Cluster.Node and have it stored in the IConnection.Config and available to all Node connection requests.

Anyway, review at your at your convenience and let me know if any changes are requested.

Thanks,

Joe Hopkins
jhopkins@mediatrust.com

### CODE REVIEW

**Comment by danwashusen** [comment]
Hi Joe,
Looking good!  I do have a few comments and requests before I merge it into Pelops...
- It seems like all the integration tests will now run with authentication turned on.  I'd really like to see if we can isolate the tests for authentication so that those running without authentication (me) are still covered...  I understand there are issues with the embedded Cassandra instance that prevent it from shutting down once started.  Maybe we could start a separate instance for the auth tests?
- Could you convert the exception handling in Connection to use org.scale7.cassandra.pelops.exceptions.IExceptionTranslator.ExceptionTranslator?

Cheers,
Dan

**Comment by joethopkins** [comment]
Hi Dan,

I was on the fence about having all the integration tests run with authentication vs starting a second instance.  I will see how starting a separate embedded server for authentication tests works out to isolate.  Then add some basic tests to verify that authentication is working.

I will update the exception handling as well.

Thanks,

Joe

**Comment by joethopkins** [comment]
Hi Dan,

I updated the exception handling in Connection to use IExceptionTranslator.ExceptionTranslator.  I also backed out the EmbeddedCassandraServer authentication settings and added a couple of Unit tests to the Cluster tests to verify the ConnectionAuthenticator setup. 

I'm wrestling a bit with getting a second Embedded server to start.  If I can get it to work I will add some integration tests.  The second server seems to be finding the first servers configuration even though I gave it new ports and its own base directory.  

Thanks,

Joe

**Comment by danwashusen** [comment]
Hi Joe,
I've merged this into the 0.7.x branch and master and published a new 0.7.x-1.1 snapshot (scale7-pelops-1.1-0.7.x-20110401.044948-2).  Let me know if you have any issues...

Cheers,
Dan

**Comment by joethopkins** [comment]
Hi Dan,

This will be a big help with my current project.

Thanks,

Joe

**Pull request closed without merging**
